#ifndef KUKADU_GENERATEDSKILLS_ALL_H
#define KUKADU_GENERATEDSKILLS_ALL_H
	#include <kukadu/generated_skills/MoveHome.hpp>
	#include <kukadu/generated_skills/OpenHand.hpp>
	#include <kukadu/generated_skills/CloseHand.hpp>
	#include <kukadu/generated_skills/KinestheticTeaching.hpp>
	#include <kukadu/generated_skills/ChangeStiffness.hpp>
	#include <kukadu/generated_skills/PushHandPos.hpp>
	#include <kukadu/generated_skills/BlockingPos.hpp>
	#include <kukadu/generated_skills/RightHandBlocking.hpp>
	#include <kukadu/generated_skills/ChangeModeToIMP.hpp>
	#include <kukadu/generated_skills/WaitForReached.hpp>
	#include <kukadu/generated_skills/PushForward.hpp>
	#include <kukadu/generated_skills/FinalPush.hpp>
	#include <kukadu/generated_skills/SimpleJointPtp.hpp>
	#include <kukadu/generated_skills/ShelfAlignment.hpp>
	#include <kukadu/generated_skills/ShelfPlacementController.hpp>
	#include <kukadu/generated_skills/DropInBoxController.hpp>
	#include <kukadu/generated_skills/PressButtonController.hpp>
	#include <kukadu/generated_skills/SensingSlide.hpp>
	#include <kukadu/generated_skills/SensingPoke.hpp>
	#include <kukadu/generated_skills/PushTranslation.hpp>
	#include <kukadu/generated_skills/BookGrasping.hpp>
#endif
