#include <kukadu/learning/clustering/kmeans.hpp>
#include <kukadu/learning/metric_learning/metriclearner.hpp>
#include <kukadu/learning/regression/gaussiankernel.hpp>
#include <kukadu/learning/regression/gaussianprocessregressor.hpp>
#include <kukadu/learning/regression/generalfitter.hpp>
#include <kukadu/learning/regression/generickernel.hpp>
#include <kukadu/learning/regression/kernelregressor.hpp>
#include <kukadu/learning/regression/lwrregressor.hpp>
#include <kukadu/learning/regression/quadratickernel.hpp>
#include <kukadu/learning/regression/tricubekernel.hpp>
#include <kukadu/learning/rl/costcomputer.hpp>
#include <kukadu/learning/rl/dmpreinforcer.hpp>
#include <kukadu/learning/rl/dmprewardcomputer.hpp>
#include <kukadu/learning/rl/generalreinforcer.hpp>
#include <kukadu/learning/rl/gradientdescent.hpp>
#include <kukadu/learning/rl/power.hpp>
#include <kukadu/learning/rl/samplerewardcomputer.hpp>
#include <kukadu/learning/rl/terminalcostcomputer.hpp>
#include <kukadu/learning/rl/trajectorybasedreward.hpp>
#ifndef USEBOOST
#include <kukadu/learning/projective_simulation/core.hpp>
#include <kukadu/learning/projective_simulation/clips.hpp>
#endif
