#include <kukadu/learning/rl/dmprl.hpp>
#include <kukadu/learning/rl/policyrl.hpp>
#include <kukadu/learning/clustering/kmeans.hpp>
#include <kukadu/learning/regression/kernel.hpp>
#include <kukadu/learning/classification/classifier.hpp>
#include <kukadu/learning/projective_simulation/core.hpp>
#include <kukadu/learning/projective_simulation/clips.hpp>
#include <kukadu/learning/metric_learning/metriclearner.hpp>
#include <kukadu/learning/classification/libsvmclassifier.hpp>
#include <kukadu/learning/projective_simulation/visualization.hpp>
